### ISSUE TITLE
random keypresses when holding third button down on the left side. 

### ISSUE THREAD

**Issue by tigerteeth** [adafruit/Adafruit-NeoTrellis-M4-PCB-and-Enclosure#1]
hi, I'm using the neotrellis m4 as a macropad, sending key presses via USB. The code I am using is from adapted from this page https://learn.adafruit.com/launch-deck-trellis-m4/code-with-circuitpython

When I hold the third button down on the left (and especially if i give it a wiggle) the device sends random keypresses (always keys from the third row of the device). Is there a problem with my board? The problem is reproducible and consistent. 

I updated everything (as of 18 jan 2023) and followed all the instructions to get the device running properly.

**Comment by TheKitty** [comment]
Please post your query to https://learn..adafruit.com for product support.

**Comment by tigerteeth** [comment]
what's that url?

**Comment by TheKitty** [comment]
https://forums.adafruit.com
